.TH SPRY 1 "December 2025" "0.109.2" "Spry Manual"
.SH NAME
spry \- Spry CLI - A declarative web application framework
.SH SYNOPSIS
.B spry
[\fIOPTIONS\fR] [\fICOMMAND\fR]
.SH DESCRIPTION
Spry CLI is a command-line interface for managing Spry applications.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show this help message and exit.
.TP
.BR \-V ", " \-\-version
Show the version number.
.SH COMMANDS
.TP
.B axiom
Spry Axiom Explorer CLI.
.TP
.B rb
Spry Runbook operator.
.TP
.B sp
Spry SQLPage Playbook operator.
.TP
.B completions
Generate shell completions.
.SH AUTHOR
Spry Team
